version: '3.8'

services:
  pulscen-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - DISPLAY=:99
    volumes:
      - ./output:/app/output
      - ./json:/app/json
      - ./.env:/app/.env
    restart: unless-stopped
    container_name: pulscen-service